### ISSUE TITLE
PacSAFE fails to start if data folders not present

### ISSUE THREAD

**Issue by wcarthur** [sopac/PacSAFE#4]
```
OSError: [Errno 2] No such file or directory: '/home/tcrm/data/FJ' 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/tcrm/.qgis2/python/plugins/PacSAFE/__init__.py", line 39, in classFactory
    return PacSafe(iface)
  File "/home/tcrm/.qgis2/python/plugins/PacSAFE/PacSafe.py", line 111, in __init__
    self.updateProjectList(0)
  File "/home/tcrm/.qgis2/python/plugins/PacSAFE/PacSafe.py", line 141, in updateProjectList
    for f in os.listdir(prjPath):
OSError: [Errno 2] No such file or directory: '/home/tcrm/data/FJ'
```

This error occurs when using a clean installation of QGIS, and when trying to run the PacSAFE plugin.

If the data folders are not immediately available, the plugin fails to load. In `updateProjectList()`, there is an implicit assumption that the data folders exist (which are also presumed to be in the current working directory). 

Need to handle the situation that the data folders are not in this location. e.g. maybe have a GUI item to select the data path.

**Comment by wcarthur** [comment]
Fixed in PR #5
